### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by jryu01**

### CODE REVIEW

**Comment by bakcho** [comment]
Hi @jryu01 and @darionco  ! I see you have been actively contributing to this Visual!

I just love the the Facet Visual and see so many possibilities as when used as  Slicer! I was trying to make some enhancements myself, but this is very new to mine.

Could I suggest some enhancements request to you?
1. Option to set font size for Headers, Facet. At fullscreen, the Facet fonts look really big somethings and tis this limits the number of values shown too.
2. The "Range Value" feature is the  best thing I have seen in a BI tool! Right now, its just shows a blue bar of different ranges. Could we have an option, that when the mouse is hovered over it, it shows you the underlying Values too in a Tool Tip format? 
3. Again on the Range option. When I slide the two handles, the last text disappears on all Ranges. This doesnt get Reset until you resize the Visual. Do you think you can look into this bug please? 
4. Font Awesome icon: Again a GREAT feature. However right now it allows depends on a Column to populate its icon. Can there be a way where I enter my own FA icon name directly into the property window ?
5. Finally, could we have an option to hide the Search Box? Sometime I have less than 5 items in the FacetKey, in such case we would not need a Search box :)

I hope my request doesnt sound like a lot. But I believe this will greatly enhance the visual! :)

Thanks again for your support

**Comment by darionco** [comment]
Hello @SamRockX, Thank you for your feedback!

Let me answer your suggestions/requests one by one:

1. I think this is a good idea, especially because Power BI applies its own scaling to the visuals so every screen will display the visuals differently depending on physical size and pixel density. I'll add this to our backlog.

2. Yet again, a good idea, we were debating how to display values when they get binned like that and I think this is probably the best solution so far. I'll add it to our back log as well.

3. This is a known bug and is scheduled to be fixed.

4. This one would be difficult, because I can't imagine how this would be used for large data sets. Could you share your idea in more detail? (how exactly would you specify an icon for an entity)

5. Hiding the search box is a good suggestion but it would fall under low priority, so I'll add it to the backlog but wouldn't expect to see it implemented in the near future (unless it turns out to be a 5 minute fix)

All that being said, we are cooking big updates for some of our other visuals and, although Facet Key is being actively supported, we won't get to make these changes immediately, maybe @jryu01  can share his ideas/availability too?

**Comment by SamRockX** [comment]
@darionco Thank you for a super quick response. 
I am glad to know that you liked some of my suggestions. 
On Point #4, its not really a huge request, but I will tell you from where I am coming. I am primarily using the FacetKey visual as  Slicer, due to the fact that it allows me to Search, Select, segment, filter, and even have metrics (like count, sum of another field!!) These are amazing features to have in a Slicer. It changes the way my user filter their data. The icon feature I requested is similar to assigning a "Background color" or Font size. Alternative to assigning a Column (having FA icon name), if I could also specify my own text, it would remove the need to create a "icon" column only for this purpose. 

I have another suggestion too (related to using this as a Slicer)
#6 I know the FacetKey example showed a great way of listing multiple categories of name. But usually our data is not in this format. I have Columns like, Regions, Country,  Quarters, Department etc, which I would like to show as a Single visual (similar to your example) instead of having multiple Slicers components. This allows us to easily manage the Dashboard and makes it look good as well. If we could some how group all our filters into one FacetKey component it would be the best things PowerBI can provide! :)
Eg:

# **STATES**
## State1
10,000
## State2
1000
## State3
988

# **DEPT**
## Dept1
14000
## Dept2
12000
## Dept3
1988

Again thanks a lot of responding, I am confident you and your team are bringing out loads of great stuff for us :)
Within my Org, I am fighting for PowerBI against Qlikview, Tableau, Qliksense. I want PowerBI dashboard to drop everyone's jaw :D

**Comment by jryu01** [comment]
Thanks for giving great suggestions @SamRockX, as @darionco replied, we will add 1,2,3 to the backlog and work on them on next iteration. 

In addition to that, I guess #5 is pretty easy and can be done with simple change. We can have an option in formatting pane to enable/disable the search box.  I'll put this in the backlog and aim to include this on the next release. 

And for # 4, I think the best way to implement this is to add an option for each facet category in formatting pane so that you can configure your own font awesome class but this is bit challenging and not 100% sure it's even possible given that pbi give us limited access to configure things in that pane and the way we power our visual in pbi. But since I agree that it's nice to have feature. I'll have some time to investigate this more. 

And finally, # 6 seems it requires pretty big change and we don't have plan to implement this at this moment but we can revisit this later if there are more requests. One workaround, for now, would be formatting data in a way that it includes all the categories that you want in a column and use that column as a facet key. 

Also, I would be appreciated if you open a Github issue on Issues section with this request along with further feature/requests or bugs if you have any.

**Pull request merged**
